### ISSUE TITLE
Double tokenisation

### ISSUE THREAD

**Issue by vandijkstef** [bagbyte/use-private-action#1]
Hey, awesome action, but most actions probably already use token. Currently using this Im seeing actions as my own user, not as github-bot. I've forked and renamed it into pattoken, which allows for token usage in other actions, and will perform those actions as the github bot.

Please review vandijkstef/use-private-action@v0.0.2

**Comment by bagbyte** [comment]
Hi, sorry for the delay.
I'm not sure I got you 100% here. I saw in your code you add a reference to a new parameter (which is not declared in `action.yml`) called **pattoken**, but I don't see the difference with my code (unless this is a reserved/special parameter name?), because at the end it's just the name of the parameter, what really matters is the value you assign to it when using the action

**Comment by vandijkstef** [comment]
A lot of actions use 'token' to authenticate actions, like placing comments.

Since this was also the 'key' of the token your action uses to authenticate into private repos, it was passed on, and other actions started to do things as the user that created the Private Access Token.

I wanted to have the other actions to act as 'Github bot', which has enough permissions to place comments on the current repo's PR's. Since we don't have our own bot account, and we really didn't want to use a real user.

**Comment by bagbyte** [comment]
I've released a new version, thanks for the feedback
